name: "Ollama"
description: "Get up and running with large language models"
# renovate: datasource=github-tags depName=ollama/ollama
version: "0.2.4"
slug: "ollama"
arch:
  - aarch64
  - amd64
url: https://ollama.com
environment:
  OLLAMA_MODELS: "/config/ollama"
  # Keep model loaded in memory
  OLLAMA_KEEP_ALIVE: "-1"
map:
  - config:rw
image: docker.io/ollama/ollama
init: false
ingress: true
ingress_port: 11434
ingress_stream: true
ports:
  11434/tcp: 11434
ports_description:
  11434/tcp: "Ollama API"
startup: application
watchdog: tcp://[HOST]:[PORT:11434]
devices:
  - /dev/dri/renderD128
  - /dev/apex_0
  - /dev/apex_1
  - /dev/apex_2
  - /dev/apex_3
  - /dev/dri/card0
  - /dev/vchiq
  - /dev/video10
  - /dev/video0
tmpfs: true
usb: true
video: true
full_access: true
privileged:
  - PERFMON
